#   Version 20170103

# khulnasoft-launch.conf contains values used at startup time, by the khulnasoft
# command and by windows services.
#

# Note: this conf file is different from most khulnasoft conf files.  There is
# only one in the whole system, located at
# $KHULNASOFT_HOME/etc/khulnasoft-launch.conf; further, there are no stanzas,
# explicit or implicit.  Finally, any khulnasoft-launch.conf files in
# etc/apps/... or etc/users/... will be ignored.


# Lines beginning with a # are considered comments and are ignored.

#*******
# Environment variables
#
# Primarily, this file simply sets environment variables to be used by
# Khulnasoft programs.
#
# These environment variables are the same type of system environment
# variables that can be set, on unix, using:
#   bourne shells:
#       $ export ENV_VAR=value
#   c-shells:
#       % setenv ENV_VAR value
#
# or at a windows command prompt:
#   C:\> SET ENV_VAR=value
#*******

<environment_variable>=<value>

* Any desired environment variable can be set to any value.
  Whitespace is trimmed from around both the key and value.
* Environment variables set here will be available to all khulnasoft processes,
  barring operating system limitations.


#*******
# Specific Khulnasoft environment settings
#
# These settings are primarily treated as environment variables, though some
# have some additional logic (defaulting).
#
# There is no need to explicitly set any of these values in typical
# environments.
#*******

KHULNASOFT_HOME=<pathname>
* The comment in the auto-generated khulnasoft-launch.conf is informational, not
  a live setting, and does not need to be uncommented.
* Fully qualified path to the Khulnasoft install directory.
* If unset, Khulnasoft automatically determines the location of KHULNASOFT_HOME
  based on the location of the khulnasoft CLI executable.
    * Specifically, the parent of the directory containing khulnasoft or khulnasoft.exe
* Must be set if Common Criteria mode is enabled.
* NOTE: Khulnasoft plans to submit Khulnasoft Enterprise for Common Criteria
  evaluation. Khulnasoft does not support using the product in Common
  Criteria mode until it has been certified by NIAP. See the "Securing
  Khulnasoft Enterprise" manual for information on the status of Common
  Criteria certification.
* Defaults to unset.

KHULNASOFT_DB=<pathname>
* The comment in the auto-generated khulnasoft-launch.conf is informational, not
  a live setting, and does not need to be uncommented.
* Fully qualified path to the directory containing the khulnasoft index
  directories.
* Primarily used by paths expressed in indexes.conf
* The comment in the autogenerated khulnasoft-launch.conf is informational, not
  a live setting, and does not need to be uncommented.
* If unset, becomes $KHULNASOFT_HOME/var/lib/khulnasoft (unix) or
     %KHULNASOFT_HOME%\var\lib\khulnasoft (windows)
* Defaults to unset.

KHULNASOFT_BINDIP=<ip address>
* Specifies an interface that khulnasoftd and khulnasoftweb should bind to, as
  opposed to binding to the default for the local operating system.
* If unset, Khulnasoft makes no specific request to the operating system when
  binding to ports/opening a listening socket.  This means it effectively
  binds to '*'; i.e.  an unspecified bind.  The exact result of this is
  controlled by operating system behavior and configuration.
* NOTE: When using this setting you must update mgmtHostPort in web.conf to
  match, or the command line and khulnasoftweb will not know how to
  reach khulnasoftd.
* For khulnasoftd, this sets both the management port and the receiving ports
  (from forwarders).
* Useful for a host with multiple IP addresses, either to enable
  access or restrict access; though firewalling is typically a superior
  method of restriction.
* Overrides the Khulnasoftweb-specific web.conf/[settings]/server.socket_host
  param; the latter is preferred when KhulnasoftWeb behavior is the focus.
* Defaults to unset.

KHULNASOFT_IGNORE_SELINUX=true
* If unset (not present), Khulnasoft on Linux will abort startup if it detects
  it is running in an SELinux environment.  This is because in
  shipping/distribution-provided SELinux environments, Khulnasoft will not be
  permitted to work, and Khulnasoft will not be able to identify clearly why.
* This setting is useful in environments where you have configured SELinux
  to enable Khulnasoft to work.
* If set to any value, Khulnasoft will launch, despite the presence of SELinux.
* Defaults to unset.

KHULNASOFT_OS_USER = <string> | <nonnegative integer>
* The OS user whose privileges Khulnasoft will adopt when running, if this
  parameter is set.
* Example: KHULNASOFT_OS_USER=fnietzsche, but a root login is used to start
  khulnasoftd. Immediately upon starting, khulnasoftd abandons root's privileges,
  and acquires fnietzsche's privileges; any files created by khulnasoftd (index
  data, logs, etc.) will be consequently owned by fnietzsche.  So when
  khulnasoftd is started next time by fnietzsche, files will be readable.
* When 'khulnasoft enable boot-start -user <U>' is invoked, KHULNASOFT_OS_USER
  is set to <U> as a side effect.
* Under UNIX, username or apposite numeric UID are both acceptable;
  under Windows, only a username.

#*******
# Service/server names.
#
# These settings are considered internal, and altering them is not
# supported.
#
# Under Windows, they influence the expected name of the service; on UNIX
# they influence the reported name of the appropriate server or daemon
# process.
#
# If you want to run multiple instances of Khulnasoft as *services* under
# Windows, you will need to change the names below for 2nd, 3rd, ...,
# instances.  That is because the 1st instance has taken up service names
# 'Khulnasoftd' and 'Khulnasoftweb', and you may not have multiple services with
# same name.
#*******

KHULNASOFT_SERVER_NAME=<name>
* Names the khulnasoftd server/service.
* Defaults to khulnasoftd (UNIX), or Khulnasoftd (Windows).

KHULNASOFT_WEB_NAME=<name>
* Names the Python app server / web server/service.
* Defaults to khulnasoftweb (UNIX), or Khulnasoftweb (Windows).
